### ISSUE TITLE
Schmuck-Video? ... 9.1.2.1 Alternativen für Audiodateien und stumme Videos

### ISSUE THREAD

**Issue by anatom5** [BIK-BITV/BIK-App-Test#136]
Hallo zusammen, ich habe gerade den aus meiner Sicht seltenen Fall, dass in einem Header ein Schmuck-Video eingebunden wird. Zumindest besteht das Video eigentlich nur aus Bildsequenzen, die mehr eine Art Bildergalerie darstellen. Wenn es nur ein einzelnes Bild wäre, würde ich es sogar als Schmuckbild bewerten. Gibt es in diesem Prüfschritt einen Hinweis auf mögliche Schmuckvideos?  Dass das Video selbst keinen Start-Stopp-Button hat und an anderer Stelle sowieso durchfallen würde, steht auf einem anderen Blatt. Aber beim Prüfschritt „Alternativen“ tue ich mich schwer, für einen relativ nichtssagenden Bilderwechsler, der halt als Videoelement umgesetzt wurde, eine vollständige Transkription zu verlangen. Bin gespannt auf eure Einschätzung.

**Comment by johannesFischer84** [comment]
Meine Meinung dazu: Entweder könnte man das dekorative Video mit `aria-hidden=true` für assistive Technologien ausblenden, analog dem Ausblenden bei dekorativen Grafiken. Dann braucht man auch keine Alternative für stumme Videos mehr.
Alternativ könnte man mit `aria-label` kurz schreiben, dass es sich um beliebige animierte Bilder handelt oder so ähnlich.

**Comment by sweckenmann** [comment]
@anatom5 Geht es hier um Web oder App? Bei einer Bildergalerie würde ich in der Regel schon Alternativtexte fordern. Aber bei einem Video ist das weniger praktikabel machbar, da finde ich den Vorschlag mit dem `aria-label` ganz gut. Man könnte darüber ja eine kurze Zusammenfassung liefern.

**Comment by detlevhfischer** [comment]
Es muss wohl um Web gehen. Ich schließe deshalb dieses Issue.
