### ISSUE TITLE
11.1.3.1a Info und Beziehungen – Überschriften

### ISSUE THREAD

**Issue by sprungmarker** [BIK-BITV/BIK-App-Test#138]
> Android-Entwickler haben derzeit keine Möglichkeit unterschiedliche Überschriftsebenen in nativen Ansichten auszuzeichnen. Eine fehlende Auszeichnung von Überschriftsebenen wird daher nicht negativ bewertet.

Das scheint nicht mehr wirklich aktuell zu sein:
[Principles for improving app accessibility](https://developer.android.com/guide/topics/ui/accessibility/principles#headings_within_text)

**Comment by detlevhfischer** [comment]
Hallo @sprungmarker, danke für den Hinweis, ich habe den Text etwas angepasst: https://github.com/BIK-BITV/BIK-App-Test/pull/139

**Comment by stefanFarnetani** [comment]
@detlevhfischer ich würde keine Code-Hinweise in den Prüfkatalog einfügen. Das ist aktuell viel zu schnelllebig und flüchtig auf mobilen Geräten. Insbesondere Android zeichnet sich darüber aus, dass es mehrere Möglichkeiten gibt eine App zu programmieren. Allein die offiziell unterstützen Varianten von Android zählen drei Varianten: XML-Notition (die zitierte Version), Kotlin-Version und die jetpack-Variante. Dazu kommen solche Sachen wie flutter oder react natice ...

Was alle aktuell eint, ist, dass die Accessibility Modell von Android keine heading level kennt. Ich würde es den Text einfach allgemein halten.
