### ISSUE TITLE
11.2.4.3 Fokusreihenfolge und dynamische Elemente (Dialoge)

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-App-Test#20]
Im Prüfung-Bereich steht unter anderem folgender Satz:
`Falls dynamische Inhalte eingefügt werden können, wird geprüft, ob die Reihenfolge nach der Einfügung noch immer sinnvoll ist.`

Meiner Meinung nach sollte das genauer erklärt werden. Man könnte zum Beispiel Folgendes im Anschluss ergänzen:
"Dies ist bei eingeblendeten Dialogen in der Regel der Fall,
1. wenn sich der Fokus bei Aufruf am Beginn des Dialogs befindet,
2. wenn der Fokus sich nur innerhalb des Dialogs bewegt, solange der Dialog sichtbar ist,
3. wenn der Fokus sich nach dem Schließen des Dialogs wieder an der aufrufenden Stelle befindet."

**Comment by detlevhfischer** [comment]
@johannesFischer84 Deine Ergänzung ist jetzt in der Prüfanleitung drin, die ich ohnehin jetzt in einzelne Punkte aufgeteilt habe (die Wischgesten-Problematik habe ich erstmal wieder entfernt, ich denke, vielleicht gehört das besser in einen eigenen Prüfschritt).
