### ISSUE TITLE
11.3.2.2 Kontextänderung Eingabe: Wozu Hinweis auf modale Dialoge?

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-App-Test#25]
Im Bereich "Hinweise" steht folgender Satz:
> Auftretende modale Dialoge müssen dabei barrierefrei sein.

Was haben modale Dialoge mit möglicher Kontextänderungen bei der Änderung des Werts eines Bedienelements zu tun? Ggf. sollte der Satz entfernt werden.

**Comment by detlevhfischer** [comment]
Du hast recht, ich habe den Hinweis entfernt.
