### ISSUE TITLE
11.4.1.2 (Name, Rolle, Wert): Links zu iOS/Android-Entwicklungs-Quellen

### ISSUE THREAD

**Issue by johannesFischer84** [BIK-BITV/BIK-App-Test#26]
In Hinweisen und Quellen ist zweimal ein toter Link auf die iOS Accessibility Traits vorhanden. Richtig wären wohl folgende beiden Links:
https://developer.apple.com/documentation/uikit/uiaccessibility/uiaccessibilitytraits
https://developer.apple.com/documentation/swiftui/accessibilitytraits

Und bei Android könnte man bestimmt auf den Accessibility Service verweisen: https://developer.android.com/reference/android/accessibilityservice/package-summary

Wenn jemand noch andere passende Links hat, gerne her damit.

**Comment by detlevhfischer** [comment]
Danke, habe ich umgesetzt!
