### ISSUE TITLE
Verzichtbare Prüfschritte

### ISSUE THREAD

**Issue by helmsaccess** [BIK-BITV/BIK-App-Test#32]
Folgende Prüfschritte halte ich für verzichtbar:

11.1.1.1c Leere alt-Attribute für Layout-Grafiken
11.1.3.1c Zuordnung von Tabellenzellen.adoc
11.1.3.1d Kein Strukturmarkup für Layouttabellen.adoc

Entsprechende Bewertungen könnte man meiner Meinung nach problemlos auch in den anderen Prüfschritten der jeweiligen Prüfschrittgruppe unterbringen, also bspw. ursprüngliche 1.1.1c Bewertungen nach 1.1.1b.

So könnte man etwas Platz für neue Prüfschritte machen, z. B. für #24.

**Comment by detlevhfischer** [comment]
Wie ist das mit dem CAPTCHAs Prüfschritt (11.1.1.1d)? Iast der nicht auch verzichtbar?  Ich kann mich bei nativen Anwendungen nicht an CAPTCHAs erinnern - gibt es manchmal welche? Die Prüfung ließe sich dann wohl auch als Spezialfall in 11.1.1.1b behandeln?

**Comment by detlevhfischer** [comment]
Ich habe in PR #48 in Abschnitt 2. Prüfung einen Punkt für Schmuckgrafiken eingebaut - bitte prüfen, ob das ausreicht, um 11.1.1.1c zu löschen!

**Comment by johannesFischer84** [comment]
> Ich habe in PR #48 in Abschnitt 2. Prüfung einen Punkt für Schmuckgrafiken eingebaut - bitte prüfen, ob das ausreicht, um 11.1.1.1c zu löschen!

Dort steht:
> Prüfen, ob Schmuckgrafiken Alternativtexte tragen.

Ich würde zur Sicherheit eine Verneinung einfügen, wenn das für unerfahrene Prüfer nicht eingängig ist: "Prüfen, ob Schmuckgrafiken entsprechend keinen Alternativtext tragen."
Aus meiner Sicht bräuchte man dann 11.1.1.1c für dekorative Grafiken nicht.
