### ISSUE TITLE
11.5.2.13 Verständlichkeit der Prüfschrittbeschreibung

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-App-Test#34]
Der Text suggeriert, dass die Eingabe über Screenreader erfolgt. Die Navigation durch Text und versetzen des Fokus sind  aber Eingabeaktionen, die entweder  taktil über Touch/Gesten am Bildschirm oder externe Eingabegeräte  oder über Spracheingabe erfolgen können. 

Der Begriff Screenreader ist in diesem Kontext möglicherweise nicht verständlich oder mit fehlt hierzu Hintergrundwissen wie diese Aktionen über einen aktivierten Screenreader anders bedient werden sollen wie ohne Screenreader. 

Falls dieser Prüfschritt im Grunde nur die Tastaturbedienbarkeit in 11.2.1.1 verfeinert, indem er sich speziell auf Textnavigation und Textauswahl bezieht, die mit einem Eingabegerät durchgeführt werden kann, aber deren Positionsänderung bzw. die Textauswahl vom Screenreader entsprechend bestätigt werden muss. dann wäre es wieder besser verständlich. 

EDIT: Auch ist mir der Unterschied/die Abgrenzung zu 11.5.2.14 nicht klar.

**Comment by detlevhfischer** [comment]
@CarstenKaul Die EN bezieht sich direkt auf die programmatische Ermittelbarkeit für assistive Technologien, nicht darauf, ob bzw. wie Elemente mit Touch oder Tastatur fokussiert werden:
> make information and mechanisms necessary to
track focus, text insertion point, and selection attributes of user interface elements programmatically determinable by assistive technologies

Was die Abgrenzung zu 11.5.2.14 angeht: Hier bei 11.5.2.13 geht es um das programmatische **Auslesen** der Fokusposition, in 11.5.2.14 umd das aktive **Versetzen / Verschieben** der Position.

Können wir das Issue schließen?

**Comment by johannesFischer84** [comment]
@CarstenKaul Carsten, Spracheingabe würde vielleicht zusätzlich zum Screenreader funktionieren, da man Spracheingabe zu den assistiven Technologien zählen kann. Damit könnte man ggf. alternativ zum Screenreader testen. Aus meiner Sicht ist es mit Screenreader aber einfacher. Ansonsten stimme ich Detlev zu.

**Comment by detlevhfischer** [comment]
@CarstenKaul Ich schließe das Issue, wenn Fragen offen bleiben, gern wieder öffnen...
