### ISSUE TITLE
11.5.2.16 Abgrenzung zum Begriff "Wert" in 11.4.1.2 

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-App-Test#36]
Falls die Begriffe "Benutzerschnittstellenelemente" und "Steuerelemente" das Gleiche meinen, dann lassen sich "Zustände" und "Eigenschaften" begrifflich dem Wort "Wert" in 11.4.1.2 (Name, Rolle Wert) zuzuordnen. 

Ohne ein gutes Beispiel, dass die Abgrenzung zu 11.4.1.2 verdeutlicht, kann ich in diesem Prüfschritt keinen Mehrwert oder erkennbare Abgrenzung sehen.

**Comment by johannesFischer84** [comment]
Benutzerschnittstellenelemente (user interface elements) und Steuerelemente und Bedienelemente sind für mich tatsächlich das gleiche. In 11.5.2.16 geht es auf jeden Fall darum, dass Werte von den Bedienelementen bei Nutzung von assistiven Technologien (also z. B. mit Screenreader, Spracheingabe usw.) geändert werden können.

Falls man WCAG 4.1.2 streng auslegt, könnte man im Unterschied sagen, dass in 4.1.2 nur der Wert verfügbar sein muss (aktueller Wert wird vom Screenreader vorgelesen), dass aber nicht von Änderung des Wertes (Bedienung, Auswahl eines Werts, Eingabe usw.) die Rede ist. Wahrscheinlich wird man so nicht bewerten, aber man könnte es so interpretieren meiner Meinung nach.

Ein weiterer Unterschied ist, dass sich WCAG 4.1.2 auf die korrekte Auszeichnung bezieht, z. B. bei Webseiten native Elemente oder die Nutzung von ARIA-Attributen. Diese Auszeichnung soll der Accessibility-Schnittstelle zur Verfügung stehen. In 11.5.2.16 dagegen muss die Accessibility-Schnittstelle richtig von der Software genutzt werden. Das ist im Webseiten-Bereich Browser-Aufgabe (Browser ist die Software), im App-Bereich die App selbst als Software. Da der Quellcode der App in der Regel nicht zur Verfügung steht, wird man WCAG 4.1.2 und 11.5.2.16 im Bereich der Werte wahrscheinlich meist ähnlich bewerten.

**Comment by detlevhfischer** [comment]
@CarstenKaul  Wir sprechen ja in der Regel von "Bedienelementen" (das ist historisch so im BIK Test). Wenn andere synonyme Ausdrücke verwendet werden, die besser angeglichen wären, gern einen PR dazu machen.
