### ISSUE TITLE
12.2.3 Anwendbarkeit

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-App-Test#37]
Angegeben ist im Text aktuell: "immer anwendbar"

Sind dafür nicht folgende Voraussetzungen erforderlich?

a) mind. ein Unterstützungsdienst wird angeboten
b) in der Software sind Barrierefreiheitsfunktionen vorhanden oder es stehen Hinweise zu barrierefreien Nutzung/Einrichtung zur Verfügung, die vom Unterstützungsdienst vermittelt werden könnten.

Nur bei Vorliegen beider Kriterien wäre der Prüfschritt anwendbar.

**Comment by johannesFischer84** [comment]
In der EN 301 549 sagt aus meiner Sicht in der Regel die Precondition, wann ein Kriterium anwendbar ist. Bei der 12.2.3 steht darin nur dein Punkt a (Unterstützungsdienst wird angeboten). Daher stimme ich dir bezüglich a) zu.
