### ISSUE TITLE
12.2.4 Verständnisfrage zu Note3

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-App-Test#38]
Zitat: "NOTE 3: Where the support documentation is incorporated into the ICT, the documentation falls under the
requirements for accessibility in the present document."

Ich verstehe den Satz nicht. Was ist hier das "present document"? 

Hintergrund: Ich versuche zu verstehen wieso man zwischen Dokumenten unterscheidet, die erst vom Support auf Anfrage ausgegeben werden und denen die in der Software bereits integriert sind?

Wenn damit gemeint ist, dass die Dokumentation nicht als eigenständiges Dokument vorhanden ist, sondern z. B. als Textinformationen innerhalb der App, dann wäre doch die Anforderungen aus Kapitel 11 darauf anzuwenden, korrekt?

**Comment by johannesFischer84** [comment]
Ich verstehe unter "present document" die EN-Norm selbst. Ich bin mir aber nicht 100% sicher. Die NOTE 3 verstehe ich so: Soweit die Dokumentation in die Anwendung (IKT) integriert ist, sind die Anforderungen dieser Norm zu erfüllen.

> Ich versuche zu verstehen wieso man zwischen Dokumenten unterscheidet, die erst vom Support auf Anfrage ausgegeben werden und denen die in der Software bereits integriert sind?

Es könnte Hilfe-Dokumente geben, die zum Download in einer App angeboten werden (oder auch verlinkt auf eine Webseite). Daneben könnte der telefonische Support Spezial-Hilfe-Dokumente vorhalten, die nur bei telefonischer Beratung oder Chat-Beratung an die Nutzenden herausgegeben werden. Dadurch dass beides in der EN genannt wird, ist eine "Lücke"/Schlupfloch in der Norm unwahrscheinlicher.

> Wenn damit gemeint ist, dass die Dokumentation nicht als eigenständiges Dokument vorhanden ist, sondern z. B. als Textinformationen innerhalb der App, dann wäre doch die Anforderungen aus Kapitel 11 darauf anzuwenden, korrekt?

Ja, in dem Fall sollte die entsprechende Hilfe/Dokumentation bereits in der Auswahl für die Prüfung enthalten sein, denke ich.

**Comment by detlevhfischer** [comment]
@CarstenKaul Können wir dieses issue schließen?
