### ISSUE TITLE
11.1.1.1c Leere alt-Attribute für Layout-Grafiken streichen?

### ISSUE THREAD

**Issue by detlevhfischer** [BIK-BITV/BIK-App-Test#49]
Ich denke, man könnte diesen Prüfschritt streichen und bei 11.1.1.1a und 11.1.1.1b mitprüfen.
Bei 11.1.1.1a gige es darum, es wird nichts ausgegeben. Ich habe in der Überarbeitung #47 aber auch die Empfehlung hinzugefügt, dass nichtr info-tragende Grafikelemente gar nicht den Lesefokus des Screenreaders bekommen (also inert sind). Was für Tehcniken hierfür nativ genutzt werden, weiß ich nicht, muss vielleich tauch hier nicht konkret benannt werden.
Bei 11.1.1.1b könnte man ergänzen, dass Grafiken ohne Informatonsgehalt keinen Alternativtext haben sollten, oder bei Grenzfällen (etwa dekorativen Landschaften) einen haben können oder auch nicht.

**Comment by johannesFischer84** [comment]
Ja, die dekorativen Grafiken passen gut bei 11.1.1.1a/b rein. Dass nicht info-tragende Grafikelemente gar nicht den Lesefokus des Screenreaders erhalten, könnte man doch ebenso bei 11.1.1.1b eintragen. Dort ist es aus meiner Sicht auch sinnvoller als im a-Prüfschritt der Bedienelemente. Denn wenn eine Grafik eine Aktion auslöst (Bedienelement), dann kann die Grafik gar nicht dekorativ sein.
