### ISSUE TITLE
11.3.1.1 Sprache lässt sich in der App ändern. Wie wird geprüft?

### ISSUE THREAD

**Issue by CarstenKaul** [BIK-BITV/BIK-App-Test#58]
Textvorschlag zum Prüfvorgehen:

Falls die Anwendung eine Spracheinstellung anbietet, ändern Sie die Sprache und prüfen Sie ob der Screenreader auf die neue Einstellung korrekt reagiert. (Starten Sie gegebenfalls die App dafür neu?!).
Reagiert der Screenreader nicht auf die Sprachänderung, dann wird die Sprache vermutlich nicht korrekt an den Screenreader übertragen und der Prüfschritt ist nicht erfüllt. Stellen Sie sicher, dass die Sprachdateien für die gewählte Sprache auch im Screenreader vorhanden sind , indem Sie diese im Betriebssystem als Systemsprache ändern und testen.

**Comment by sweckenmann** [comment]
@CarstenKaul Wir haben den Prüfschritt entsprechend PR von @johannesFischer84 aktualisiert https://github.com/BIK-BITV/BIK-App-Test/blob/master/Pr%C3%BCfschritte/de/11.3.1.1%20Hauptsprache%20angegeben.adoc Kann das issue damit geschlossen werden?
